AWSTemplateFormatVersion: '2010-09-09'

Description: Overarching CF Template to Create AEM Stack Manager Resources Stacks

Parameters:

  MainStackPrefixParameter:
    Type: String
    Description: The AEM Stack Main Resources Stack Prefix

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data file

  S3DataStackManagerPrefix:
    Type: String
    Description: Prefix within the Bucket to Locate Files

  DynamoDBTTLAttribute:
    Type: String
    Default: 'ttl'

  LiveSnapshotsPurgeSchedule:
    Type: String
    Description: CloudWatch Event Rule Schedule to Purge Old Live Snapshots
    Default: cron(10 20 1/3 * ? *)

  OfflineSnapshotsPurgeSchedule:
    Type: String
    Description: CloudWatch Event Rule Schedule to Purge Old Offline Snapshots
    Default: cron(15 19 ? * SUN *)

  OrchestrationSnapshotsPurgeSchedule:
    Type: String
    Description: CloudWatch Event Rule Schedule to Purge Old Orchestration Snapshots
    Default: cron(5 0/4 * * ? *)

  LiveSnapshotsPurgeInput:
    Type: String
    Description: Parameters for Purging Live Snapshot in JSON Formatted String
    Default: '"SnapshotType": "live", "Age": "1d"'

  OfflineSnapshotsPurgeInput:
    Type: String
    Description: Parameters for Purging Offline Snapshot in JSON Formatted String
    Default: '"SnapshotType": "offline", "Age": "1w"'

  OrchestrationSnapshotsPurgeInput:
    Type: String
    Description: Parameters for Purging Orchestration Snapshot in JSON Formatted String
    Default: '"SnapshotType": "orchestration", "Age": "4h"'

Resources:

  InstanceProfilesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/instance-profiles.yaml
      Parameters:
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        S3DataStackManagerPrefix:
          Ref: S3DataStackManagerPrefix

  StackManagerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - InstanceProfilesStack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-manager.yaml
      Parameters:
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        S3DataStackManagerPrefix:
          Ref: S3DataStackManagerPrefix
        DynamoDBTTLAttribute:
          Ref: DynamoDBTTLAttribute

  UtilitiesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - InstanceProfilesStack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/utilities.yaml
      Parameters:
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        S3DataStackManagerPrefix:
          Ref: S3DataStackManagerPrefix
        LiveSnapshotsPurgeSchedule:
          Ref: LiveSnapshotsPurgeSchedule
        OfflineSnapshotsPurgeSchedule:
          Ref: OfflineSnapshotsPurgeSchedule
        OrchestrationSnapshotsPurgeSchedule:
          Ref: OrchestrationSnapshotsPurgeSchedule
        LiveSnapshotsPurgeInput:
          Ref: LiveSnapshotsPurgeInput
        OfflineSnapshotsPurgeInput:
          Ref: OfflineSnapshotsPurgeInput
        OrchestrationSnapshotsPurgeInput:
          Ref: OrchestrationSnapshotsPurgeInput
