AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda Functions for utility tasks with Default Schedule Using AWS
  Events
Outputs:
  PurgeSnapshotDevAliasArn:
    Description: Arn for Prod Alias of Snapshot Purge Function
    Value:
      Ref: LambdaProdAlias
  PurgeSnapshotFunctionName:
    Description: Lambda Function Name for Snapshot Purge Function
    Value:
      Ref: SnapshotsPurgeLambdaFunction
  PurgeSnapshotProdAliasArn:
    Description: Arn for Prod Alias of Snapshot Purge Function
    Value:
      Ref: LambdaProdAlias
Parameters:
  DataBucketNameParameter:
    Description: Bucket Name that Stores Files Used by the Function
    Type: String
  LiveSnapshotsPurgeInput:
    Default: 1d
    Description: Parameters for Purging Live Snapshot in JSON Formatted String
    Type: String
  LiveSnapshotsPurgeSchedule:
    Default: cron(10 20 1/3 * ? *)
    Description: CloudWatch Event Rule Schedule to Purge Old Live Snapshots
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Main Resources Stack Prefix
    Type: String
  OfflineSnapshotsPurgeInput:
    Default: 1w
    Description: Parameters for Purging Offline Snapshot in JSON Formatted String
    Type: String
  OfflineSnapshotsPurgeSchedule:
    Default: cron(15 19 ? * SUN *)
    Description: CloudWatch Event Rule Schedule to Purge Old Offline Snapshots
    Type: String
  OrchestrationSnapshotsPurgeInput:
    Default: 4h
    Description: Parameters for Purging Orchestration Snapshot in JSON Formatted String
    Type: String
  OrchestrationSnapshotsPurgeSchedule:
    Default: cron(5 0/4 * * ? *)
    Description: CloudWatch Event Rule Schedule to Purge Old Orchestration Snapshots
    Type: String
  S3DataStackManagerPrefix:
    Description: Prefix within the Bucket to Locate Files
    Type: String
Resources:
  InitialVersion:
    Properties:
      Description: Initial Version to Start With
      FunctionName:
        Ref: SnapshotsPurgeLambdaFunction
    Type: AWS::Lambda::Version
  LambdaDevAlias:
    Properties:
      Description: Lambda Alias for Development Use
      FunctionName:
        Ref: SnapshotsPurgeLambdaFunction
      FunctionVersion: $LATEST
      Name: dev
    Type: AWS::Lambda::Alias
  LambdaProdAlias:
    Properties:
      Description: Lambda Alias for Production Use
      FunctionName:
        Ref: SnapshotsPurgeLambdaFunction
      FunctionVersion:
        Fn::GetAtt: InitialVersion.Version
      Name: prod
    Type: AWS::Lambda::Alias
  LiveSnapshotLambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: LambdaProdAlias
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt: LiveSnapshotsPurgeRule.Arn
    Type: AWS::Lambda::Permission
  LiveSnapshotsPurgeRule:
    Properties:
      Description: Delete AEM Live Snapshots Regularly
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-LiveSnapshotsPurge
      ScheduleExpression:
        Ref: LiveSnapshotsPurgeSchedule
      State: ENABLED
      Targets:
      - Arn:
          Ref: LambdaProdAlias
        Id: LiveSnapshotsPurgeRule
        Input:
          Fn::Sub: '{"SnapshotType": "live", "Age": "${LiveSnapshotsPurgeInput}"}'
    Type: AWS::Events::Rule
  OfflineSnapshotLambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: LambdaProdAlias
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt: OfflineSnapshotsPurgeRule.Arn
    Type: AWS::Lambda::Permission
  OfflineSnapshotsPurgeRule:
    Properties:
      Description: Delete AEM Offline Snapshots Regularly
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-OfflineSnapshotsPurge
      ScheduleExpression:
        Ref: OfflineSnapshotsPurgeSchedule
      State: ENABLED
      Targets:
      - Arn:
          Ref: LambdaProdAlias
        Id: OfflineSnapshotsPurgeRule
        Input:
          Fn::Sub: '{"SnapshotType": "offline", "Age": "${OfflineSnapshotsPurgeInput}"}'
    Type: AWS::Events::Rule
  OrchestrationSnapshotLambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: LambdaProdAlias
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt: OrchestrationSnapshotsPurgeRule.Arn
    Type: AWS::Lambda::Permission
  OrchestrationSnapshotsPurgeRule:
    Properties:
      Description: Delete AEM Orchestration Snapshot Regularly
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-OrchestrationSnapshotsPurge
      ScheduleExpression:
        Ref: OrchestrationSnapshotsPurgeSchedule
      State: ENABLED
      Targets:
      - Arn:
          Ref: LambdaProdAlias
        Id: OrchestrationSnapshotsPurgeRule
        Input:
          Fn::Sub: '{"SnapshotType": "orchestration", "Age": "${OrchestrationSnapshotsPurgeInput}"}'
    Type: AWS::Events::Rule
  SnapshotsPurgeLambdaFunction:
    Properties:
      Code:
        S3Bucket:
          Ref: DataBucketNameParameter
        S3Key:
          Fn::Sub: ${S3DataStackManagerPrefix}/purge_snapshots.zip
      Description: Function to Purge AEM Old Snapshots
      FunctionName:
        Fn::Sub: ${MainStackPrefixParameter}-AemSnapshotsPurge
      Handler: purge_snapshots.handler
      MemorySize: 128
      Role:
        Fn::ImportValue:
          Fn::Sub: ${MainStackPrefixParameter}-StackManagerLambdaServiceRoleArn
      Runtime: python2.7
      Timeout: 300
    Type: AWS::Lambda::Function
