AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Author

Parameters:

  InstanceProfileStackPrefixParameter:
    Type: String
    Description: The AEM Stack Instance Profile Stack Prefix

  SecurityGroupStackPrefixParameter:
    Type: String
    Description: The AEM Stack Security Groups Resources Stack Prefix

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  AuthorLoadBalancerHealthCheckTargetParameter:
    Type: String
    Description: AEM Author ELB Health Check Target

  AuthorImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Author Image Id

  AuthorImageRootDevice:
    Type: String
    Description: The root device name for the Author Image Id
    Default: /dev/sda1

  AuthorInstanceTypeParameter:
    Type: String
    Description: The Author Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  AuthorRootVolSizeParameter:
    Type: Number
    Description: Author Instances Root EBS Volume Size

  AuthorDataVolSizeParameter:
    Type: Number
    Description: Author Instances Data EBS Volume Size

  UseAuthorDataVolSnapshotParameter:
    Type: String
    AllowedValues: [true, false]
    Description: Wheather to use the Author Snapshot Data Volume.

  AuthorDataVolSnapshotParamater:
    Type: String
    Description: The Author Data Volume Snapshot Id

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Conditions:
  UseAuthorDataVolSnapshotCondition:
    Fn::Equals:
      - Ref: UseAuthorDataVolSnapshotParameter
      - true

Resources:

  AuthorSyncDelayAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${ComputeStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: Monitors the sync delay between the Author Standby and the Author Primary
      AlarmName:
        Fn::Sub: ${ComputeStackPrefixParameter}-AuthorSyncDelayAlarm
      ComparisonOperator: GreaterThanThreshold
      MetricName: GenericJMX.delay.seconds_since_last_success
      Namespace: collectd
      Period: 60
      EvaluationPeriods: 5
      Statistic: Maximum
      Threshold: 60
      Dimensions:
      - Name: PluginInstance
        Value:
          Fn::Sub: ${ComputeStackPrefixParameter}-standby-status
      - Name: Host
        Value:
          Ref: AuthorStandbyInstance

  MultiAuthorInstanceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${ComputeStackPrefixParameter}-AlarmNotificationTopic
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${ComputeStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: Multiple Author Instances have Enterered into Service
      AlarmName:
        Fn::Sub: ${ComputeStackPrefixParameter}-MultiAuthorInstnaceAlarm
      ComparisonOperator: GreaterThanThreshold
      MetricName: HealthyHostCount
      Namespace: AWS/ELB
      EvaluationPeriods: 1
      Period: 60
      Statistic: Maximum
      Threshold: 1
      Dimensions:
        - Name: LoadBalancerName
          Value:
            Ref: AuthorLoadBalancer

  AuthorPrimaryInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: !Ref AuthorImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorDataVolSizeParameter
          VolumeType: gp2
          SnapshotId:
            Fn::If:
              - UseAuthorDataVolSnapshotCondition
              - Ref: AuthorDataVolSnapshotParamater
              - Ref: AWS::NoValue
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${InstanceProfileStackPrefixParameter}-AuthorInstanceProfile
      ImageId:
        Ref: AuthorImageParameter
      InstanceType:
        Ref: AuthorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroupIds:
      - Fn::ImportValue:
          Fn::Sub: ${ComputeStackPrefixParameter}-AuthorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      SubnetId:
        Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-AuthorSubnetA
      Tags:
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
      - Key: Name
        Value: AEM Author - Primary
      - Key: Component
        Value: author-primary
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} author-primary ${AemAwsStackProvisionerVersionParameter}\n"

  AuthorStandbyInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: !Ref AuthorImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorDataVolSizeParameter
          VolumeType: gp2
          SnapshotId:
            Fn::If:
              - UseAuthorDataVolSnapshotCondition
              - Ref: AuthorDataVolSnapshotParamater
              - Ref: AWS::NoValue
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${InstanceProfileStackPrefixParameter}-AuthorInstanceProfile
      ImageId:
        Ref: AuthorImageParameter
      InstanceType:
        Ref: AuthorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroupIds:
      - Fn::ImportValue:
          Fn::Sub: ${ComputeStackPrefixParameter}-AuthorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      SubnetId:
        Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-AuthorSubnetB
      Tags:
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
      - Key: Name
        Value: AEM Author - Standby
      - Key: Component
        Value: author-standby
      - Key: AuthorPrimaryHost
        Value:
          Fn::GetAtt: [ AuthorPrimaryInstance, PrivateIp ]
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} author-standby ${AemAwsStackProvisionerVersionParameter}\n"

  AuthorLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        Target:
          Ref: AuthorLoadBalancerHealthCheckTargetParameter
        HealthyThreshold: '2'
        UnhealthyThreshold: '2'
        Interval: '30'
        Timeout: '5'
      Instances:
      - Ref: AuthorPrimaryInstance
      - Ref: AuthorStandbyInstance
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '4502'
        Protocol: HTTP
      - LoadBalancerPort: '443'
        Protocol: HTTPS
        InstancePort: '5432'
        InstanceProtocol: HTTPS
        SSLCertificateId: 'arn:aws:acm:ap-southeast-2:918473058104:certificate/3bf6d041-025c-4b7f-a30c-c519ee63c7e0'
          # Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-PrvWildcardCertificateARN
      Scheme: internal
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupStackPrefixParameter}-AuthorELBSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      Subnets:
        - Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-AuthorSubnetA
        - Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-AuthorSubnetB
      Tags:
      - Key: Name
        Value: AEM Author Load Balancer
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter

Outputs:

  AuthorPrimaryInstance:
    Value:
      Ref: AuthorPrimaryInstance
    Description: The Author Primary Instance

  AuthorStandbyInstance:
    Value:
      Ref: AuthorStandbyInstance
    Description: The Author Standby Instance

  AuthorLoadBalancer:
    Value:
      Ref: AuthorLoadBalancer
    Description: The Author Load Balancer

  AuthorLoadBalancerDNSName:
    Value:
      Fn::GetAtt: [AuthorLoadBalancer, DNSName]
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-AuthorLoadBalancerDNSName
    Description: The Author Load Balancer

  AuthorSyncDelayAlarm:
    Value:
      Ref: AuthorSyncDelayAlarm
    Description: The Author Sync Delay Alarm
