---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create Roles for AEM Stack

Parameters:

  ComputeStackPrefixParameter:
      Type: String
      Description: The AEM Stack Compute Resources Stack Prefix

Resources:


  AuthorPublishDispatcherRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
      - PolicyName: AuthorPublishDispatcherRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:Describe*
                - ec2:CreateTags
                - ec2:AttachVolume
                - ec2:CreateVolume
                - ec2:DetachVolume
                - ec2:CreateSnapshot
                - ec2:ModifyInstanceAttribute
                - autoscaling:CreateLaunchConfiguration
                - autoscaling:DescribeLaunchConfigurations
                - autoscaling:UpdateAutoScalingGroup
                - autoscaling:CreateOrUpdateTags
                - cloudwatch:PutMetricData
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:Get*
                - s3:List*
                - s3:Put*
              Resource: "*"
            - Effect: Allow
              Action:
                - logs:*
              Resource:
                - arn:aws:logs:*:*:*
      RoleName:
        Fn::Sub: ${ComputeStackPrefixParameter}-AEMStackAuthorPublishDispatcherRole

  AuthorPublishDispatcherInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: AuthorPublishDispatcherRole
  # Currently, AWS only supports one Role per InstanceProfile
  # Hence, we can't have roles from (Author, Publish, Dispatcher) in InstanceProfile
  # See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html#cfn-iam-instanceprofile-roles

  PublishDispatcherRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: PublishDispatcherRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:CreateTags
                  - autoscaling:CreateLaunchConfiguration
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:UpdateAutoScalingGroup
                  - autoscaling:CreateOrUpdateTags
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: !Sub ${ComputeStackPrefixParameter}-AEMStackPublishDispatcherRole

  PublishDispatcherInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: PublishDispatcherRole


  PublishRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: PublishRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:AttachVolume
                  - ec2:CreateVolume
                  - ec2:DetachVolume
                  - ec2:CreateSnapshot
                  - ec2:CreateTags
                  - ec2:ModifyInstanceAttribute
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: !Sub ${ComputeStackPrefixParameter}-AEMStackPublishRole

  PublishInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: PublishRole

  AuthorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: AuthorRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:CreateTags
                  - ec2:AttachVolume
                  - ec2:CreateVolume
                  - ec2:DetachVolume
                  - ec2:CreateSnapshot
                  - autoscaling:CreateOrUpdateTags
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: !Sub ${ComputeStackPrefixParameter}-AEMStackAuthorRole


  AuthorInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: AuthorRole

  AuthorDispatcherRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: AuthorDispatcherRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:CreateTags
                  - autoscaling:CreateOrUpdateTags
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: !Sub ${ComputeStackPrefixParameter}-AEMStackAuthorDispatcherRole


  AuthorDispatcherInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: AuthorDispatcherRole

  OrchestratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: OrchestratorRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:CreateTags
                  - ec2:CreateSnapshot
                  - ec2:TerminateInstances
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: "*"
              - Effect: Allow
                Action:
                  -  sqs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - SNS:ListTopics
                  - SNS:Publish
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplate
                  - cloudformation:List*
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                Resource: "*"
              - Effect: Allow
                Action:
                  - elasticloadbalancing:Describe*
                Resource: "*"
              - Effect: Allow
                Action:
                  - autoscaling:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: !Sub ${ComputeStackPrefixParameter}-AEMStackOrchestratorRole


  OrchestratorInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: OrchestratorRole

  ChaosMonkeyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: ChaosMonkeyRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteSnapshot
                  - ec2:DescribeImages
                  - ec2:DescribeInstances
                  - ec2:DescribeSnapshots
                  - ec2:DescribeVolumes
                  - ec2:TerminateInstances
                  - ses:SendEmail
                  - elasticloadbalancing:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - autoscaling:DeleteAutoScalingGroup
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeAutoScalingInstances
                  - autoscaling:DescribeLaunchConfigurations
                Resource: "*"
              - Effect: Allow
                Action:
                  - sdb:BatchDeleteAttributes
                  - sdb:BatchPutAttributes
                  - sdb:DomainMetadata
                  - sdb:GetAttributes
                  - sdb:PutAttributes
                  - sdb:ListDomains
                  - sdb:CreateDomain
                  - sdb:Select
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:Describe*
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: !Sub ${ComputeStackPrefixParameter}-AEMStackChaosMonkeyRole


  ChaosMonkeyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: ChaosMonkeyRole

  AEMStackManagerSnapshotLambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ComputeStackPrefixParameter}-AEMSnapPurgeLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub ${ComputeStackPrefixParameter}-SnapshotsPurgeLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:Describe*"
                  - ec2:DeleteSnapshot
                Resource: "*"

Outputs:

  AuthorPublishDispatcherInstanceProfile:
    Value:
      Ref: AuthorPublishDispatcherInstanceProfile
    Description: The Author Publish Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-AuthorPublishDispatcherInstanceProfile

  PublishDispatcherInstanceProfile:
    Value:
      Ref: PublishDispatcherInstanceProfile
    Description: The Publish Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-PublishDispatcherInstanceProfile

  PublishInstanceProfile:
    Value:
      Ref: PublishInstanceProfile
    Description: The Publish Instance Profile
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-PublishInstanceProfile

  AuthorInstanceProfile:
    Value:
      Ref: AuthorInstanceProfile
    Description: The Author Instance Profile
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-AuthorInstanceProfile

  AuthorDispatcherInstanceProfile:
    Value:
      Ref: AuthorDispatcherInstanceProfile
    Description: The Author Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-AuthorDispatcherInstanceProfile

  OrchestratorInstanceProfile:
    Value:
      Ref: OrchestratorInstanceProfile
    Description: The Orchestrator Instance Profile
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-OrchestratorInstanceProfile

  ChaosMonkeyInstanceProfile:
    Value:
      Ref: ChaosMonkeyInstanceProfile
    Description: The Chaos Monkey Instance Profile
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-ChaosMonkeyInstanceProfile

  AEMStackManagerSnapshotLambdaServiceRoleArn:
    Value: !GetAtt AEMStackManagerSnapshotLambdaServiceRole.Arn
    Description: The Sack Manager Lambda Service Role ARN
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-StackManagerSnapshotLambdaServiceRoleArn

  AEMStackManagerSnapshotLambdaServiceRoleName:
    Value:
      Ref: AEMStackManagerSnapshotLambdaServiceRole
    Description: AEM StackManager Snapshot Lambda Service Role Name
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-StackManagerSnapshotLambdaServiceRoleName
