AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Orchestrator

Parameters:

  InstanceProfileStackPrefixParameter:
    Type: String
    Description: The AEM Stack Instance Profile Stack Prefix

  SecurityGroupStackPrefixParameter:
    Type: String
    Description: The AEM Stack Security Groups Resources Stack Prefix

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  OrchestratorImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Orchestrator Image Id

  OrchestratorImageRootDevice:
    Type: String
    Description: The root device name for the Orchestrator Image Id
    Default: /dev/sda1

  OrchestratorInstanceTypeParameter:
    Type: String
    Description: The Orchestrator Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  OrchestratorASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Orchestrator Availability Zone List

  OrchestratorRootVolSizeParameter:
    Type: Number
    Description: Orchestrator Instances Root EBS Volume Size

  OrchestratorDataVolSizeParameter:
    Type: Number
    Description: Orchestrator Instances Data EBS Volume Size

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

  AuthorStackName:
    Type: String
    Description: The name of the author stack.
    Default: ''

  AuthorDispatcherStackName:
    Type: String
    Description: The name of the author-dispatcher stack.
    Default: ''

  PublishStackName:
    Type: String
    Description: The name of the author stack.
    Default: ''

  PublishDispatcherStackName:
    Type: String
    Description: The name of the publish-dispatcher stack.
    Default: ''

  MessagingStackName:
    Type: String
    Description: The name of the messaging stack.
    Default: ''

  AEMASGEventQueueName:
    Type: String
    Description: The name of the messaging stack.
    Default: ''

Resources:


  OrchestratorLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: !Ref OrchestratorImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: OrchestratorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: OrchestratorDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${InstanceProfileStackPrefixParameter}-OrchestratorInstanceProfile
      ImageId:
        Ref: OrchestratorImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: OrchestratorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupStackPrefixParameter}-OrchestratorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -x
            source /etc/profile
            SB_ROOT_DIR="/opt/shinesolutions/aem-aws-stack-builder"
            mkdir -p ${!SB_ROOT_DIR}
            YAML_PREFIX="aem_orchestrator::application_properties"
            YAML_STACKNAME_PREFIX="aws_cloudformation_stack_name"
            cat > ${!SB_ROOT_DIR}/local.yaml << STACK_NAMES_YAML
            ${!YAML_PREFIX}::${!YAML_STACKNAME_PREFIX}_author: "${AuthorStackName}"
            ${!YAML_PREFIX}::${!YAML_STACKNAME_PREFIX}_author_dispatcher: "${AuthorDispatcherStackName}"
            ${!YAML_PREFIX}::${!YAML_STACKNAME_PREFIX}_publish: "${PublishStackName}"
            ${!YAML_PREFIX}::${!YAML_STACKNAME_PREFIX}_publish_dispatcher: "${PublishDispatcherStackName}"
            ${!YAML_PREFIX}::${!YAML_STACKNAME_PREFIX}_messaging: "${MessagingStackName}"
            ${!YAML_PREFIX}::aws_sqs_queue_name: "${AEMASGEventQueueName}"
            STACK_NAMES_YAML
            aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh
            chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh
            /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh \
                ${DataBucketNameParameter} \
                ${ComputeStackPrefixParameter} \
                orchestrator \
                ${AemAwsStackProvisionerVersionParameter} \
                ${!SB_ROOT_DIR}/local.yaml

  OrchestratorAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: OrchestratorASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: OrchestratorLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      Tags:
      - Key: Name
        Value: AEM Orchestrator
        PropagateAtLaunch: true
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
        PropagateAtLaunch: true
      - Key: Component
        Value: orchestrator
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              !Sub ${NetworkStackPrefixParameter}-OrchestratorSubnetList
      MetricCollection:
        -
          Granularity: "1Minute"
          Metrics:
            - "GroupMinSize"
            - "GroupMaxSize"
            - "GroupDesiredCapacity"
            - "GroupInServiceInstances"
            - "GroupPendingInstances"
            - "GroupStandbyInstances"
            - "GroupTerminatingInstances"
            - "GroupTotalInstances"

Outputs:

  OrchestratorLaunchConfiguration:
    Value:
      Ref: OrchestratorLaunchConfiguration
    Description: The Orchestrator Launch Configuration

  OrchestratorAutoScalingGroup:
    Value:
      Ref: OrchestratorAutoScalingGroup
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-OrchestratorAutoScalingGroup
    Description: The Orchestrator Auto Scaling Group
