---
- name: AEM Chaos Monkey CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Chaos Monkey Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/chaos-monkey.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          NetworkStackPrefixParameter: "{{ network_stack_prefix }}"
          SecurityGroupStackPrefixParameter: "{{ security_groups_stack_prefix }}"
          ChaosMonkeyImageParameter: "{{ ami_ids.chaos_monkey }}"
          ChaosMonkeyImageRootDevice: "{{ ami_root_device_name }}"
          ChaosMonkeyInstanceTypeParameter: "{{ chaos_monkey.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          ChaosMonkeyASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          ChaosMonkeyRootVolSizeParameter: "{{ chaos_monkey.root_vol_size }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
          AemAwsStackProvisionerVersionParameter: "{{ library.aem_aws_stack_provisioner_version }}"
          OrchestratorStackNameParameter: "{{ stack_prefix }}-{{orchestrator.stack_name}}"
          PublishStackNameParameter: "{{ stack_prefix }}-{{publish.stack_name}}"
          PublishDispatcherStackNameParameter: "{{ stack_prefix }}-{{publish_dispatcher.stack_name}}"
          AuthorDispatcherStackNameParameter: "{{ stack_prefix }}-{{author_dispatcher.stack_name}}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: >
           aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}"
               --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Chaos Monkey Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
