---
- name: AEM Roles CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Instance Profiles Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ instance_profiles.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/instance-profiles.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          AEMStackManagerVersion: "{{ stack_manager.version }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
          S3DataStackManagerPrefix: "{{ stack_prefix }}/{{ stack_manager.s3_prefix }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ instance_profiles.stack_name }}"
            --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ instance_profiles.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Roles Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ instance_profiles.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
