---

- name: Deploy AEM Snapshots Purge Cloud Native Solution
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:
    - name: >
        Create Snapshots Purge Cloud Native Solution Related Resources Using CloudFormation
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ snapshots_purge.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: false
        template: "{{ playbook_dir}}/../../../cloudformation/apps/snapshots-purge.yaml"
        template_parameters:
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
          S3DataStackManagerPrefix: "{{ stack_prefix }}/{{ stack_manager.s3_prefix }}"
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          LiveSnapshotsPurgeSchedule: "{{ snapshots_purge.LiveSnapshotsPurgeSchedule}}"
          OfflineSnapshotsPurgeSchedule: "{{ snapshots_purge.OfflineSnapshotsPurgeSchedule }}"
          OrchestrationSnapshotsPurgeSchedule: "{{ snapshots_purge.OrchestrationSnapshotsPurgeSchedule }}"
          LiveSnapshotsPurgeInput: "{{ snapshots_purge.LiveSnapshotsPurgeInput }}"
          OfflineSnapshotsPurgeInput: " {{ snapshots_purge.OfflineSnapshotsPurgeInput }}"
          OrchestrationSnapshotsPurgeInput: "{{ snapshots_purge.OrchestrationSnapshotsPurgeInput }}"
      register: stack_info
      tags:
        - create

    - name: Check if Snapshots Purge Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ snapshots_purge.stack_name }}"
             --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Snapshots Purge Stack Problem if Any
      debug:
        msg: Stack "{{ stack_prefix }}-{{ snapshots_purge.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Snapshots Purge Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{  snapshots_purge.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
        - delete
