version: 0.2

phases:
  install:
    commands:
      - make deps
  pre_build:
    commands:
      - chmod +x test/integration/test-examples.sh
  build:
    commands:
      - make test-integration-$AEM_VERSION-$OS_TYPE test_id=$BUILD_ID
