AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Bastion Host inside AEM VPC
Parameters:
  BastionImageId:
    Description: AMI Id used for Bastion Host
    Type: AWS::EC2::Image::Id
  BastionKeyPairName:
    Description: Key Pair Name for the Bastion Host
    Type: AWS::EC2::KeyPair::KeyName
  BastionSecurityGroups:
    Description: The Set of Security Groups Attached to the Bastion Host
    Type: List<AWS::EC2::SecurityGroup::Id>
  BastionSubnet:
    Description: Subnet Ids the Bastion Host Will be Launched into
    Type: AWS::EC2::Subnet::Id
  StackPrefix:
    Default: ''
    Description: Used to Namespace the Exported Resources
    Type: String
Resources:
  Bastion:
    Properties:
      ImageId:
        Ref: BastionImageId
      InstanceType: t3.micro
      KeyName:
        Ref: BastionKeyPairName
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: '0'
        GroupSet:
          Ref: BastionSecurityGroups
        SubnetId:
          Ref: BastionSubnet
      Tags:
      - Key: Name
        Value: bastion
    Type: AWS::EC2::Instance
