AWSTemplateFormatVersion: '2010-09-09'
Description: Export Network Resources to Make It Available for Other Stacks
Outputs:
  AuthorDispatcherELBSubnetA:
    Description: The Author Dispatcher ELB Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherELBSubnetA
    Value:
      Ref: AuthorDispatcherELBSubnetA
  AuthorDispatcherELBSubnetB:
    Description: The Author Dispatcher ELB Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherELBSubnetB
    Value:
      Ref: AuthorDispatcherELBSubnetB
  AuthorDispatcherELBSubnetList:
    Description: The Author Dispatcher ELB Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherELBSubnetList
    Value:
      Fn::Sub: ${AuthorDispatcherELBSubnetA},${AuthorDispatcherELBSubnetB}
  AuthorDispatcherSubnetA:
    Description: The Author Dispatcher Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherSubnetA
    Value:
      Ref: AuthorDispatcherSubnetA
  AuthorDispatcherSubnetB:
    Description: The Author Dispatcher Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherSubnetB
    Value:
      Ref: AuthorDispatcherSubnetB
  AuthorDispatcherSubnetList:
    Description: The Author Dispatcher Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherSubnetList
    Value:
      Fn::Sub: ${AuthorDispatcherSubnetA},${AuthorDispatcherSubnetB}
  AuthorPublishDispatcherSubnetA:
    Description: The Author Publish Dispatcher Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorPublishDispatcherSubnetA
    Value:
      Ref: AuthorPublishDispatcherSubnetA
  AuthorPublishDispatcherSubnetB:
    Description: The Author Publish Dispatcher Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorPublishDispatcherSubnetB
    Value:
      Ref: AuthorPublishDispatcherSubnetB
  AuthorPublishDispatcherSubnetList:
    Description: The Author Publish Dispatcher Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorPublishDispatcherSubnetList
    Value:
      Fn::Sub: ${AuthorPublishDispatcherSubnetA},${AuthorPublishDispatcherSubnetB}
  AuthorSubnetA:
    Description: The Author Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorSubnetA
    Value:
      Ref: AuthorSubnetA
  AuthorSubnetB:
    Description: The Author Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorSubnetB
    Value:
      Ref: AuthorSubnetB
  AuthorSubnetList:
    Description: The Author Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorSubnetList
    Value:
      Fn::Sub: ${AuthorSubnetA},${AuthorSubnetB}
  ChaosMonkeySubnetList:
    Description: The ChaosMonkey Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-ChaosMonkeySubnetList
    Value:
      Fn::Sub: ${ToolSubnetA}, ${ToolSubnetB}
  OrchestratorSubnetList:
    Description: The Orchestrator Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-OrchestratorSubnetList
    Value:
      Fn::Sub: ${ToolSubnetA}, ${ToolSubnetB}
  PrivateRouteTable:
    Description: The Private Route Table for AEM Stack VPC
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PrivateRouteTable
    Value:
      Ref: PrivateRouteTable
  PublicRouteTable:
    Description: The Public Route Table for AEM Stack VPC
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublicRouteTable
    Value:
      Ref: PublicRouteTable
  PublishDispatcherELBSubnetA:
    Description: The Publish Dispatcher ELB Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherELBSubnetA
    Value:
      Ref: PublishDispatcherELBSubnetA
  PublishDispatcherELBSubnetB:
    Description: The Publish Dispatcher ELB Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherELBSubnetB
    Value:
      Ref: PublishDispatcherELBSubnetB
  PublishDispatcherELBSubnetList:
    Description: The Publish Dispatcher ELB Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherELBSubnetList
    Value:
      Fn::Sub: ${PublishDispatcherELBSubnetA},${PublishDispatcherELBSubnetB}
  PublishDispatcherSubnetA:
    Description: The Publish Dispatcher Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherSubnetA
    Value:
      Ref: PublishDispatcherSubnetA
  PublishDispatcherSubnetB:
    Description: The Publish Dispatcher Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherSubnetB
    Value:
      Ref: PublishDispatcherSubnetB
  PublishDispatcherSubnetList:
    Description: The Publish Dispatcher Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherSubnetList
    Value:
      Fn::Sub: ${PublishDispatcherSubnetA},${PublishDispatcherSubnetB}
  PublishSubnetA:
    Description: The Publish Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishSubnetA
    Value:
      Ref: PublishSubnetA
  PublishSubnetB:
    Description: The Publish Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishSubnetB
    Value:
      Ref: PublishSubnetB
  PublishSubnetList:
    Description: The Publish Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishSubnetList
    Value:
      Fn::Sub: ${PublishSubnetA},${PublishSubnetB}
  ToolSubnetA:
    Description: The Tool Subnet in Availability Zone A
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-ToolSubnetA
    Value:
      Ref: ToolSubnetA
  ToolSubnetB:
    Description: The Tool Subnet in Availability Zone B
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-ToolSubnetB
    Value:
      Ref: ToolSubnetB
  ToolSubnetList:
    Description: The Tool Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-ToolSubnetList
    Value:
      Fn::Sub: ${ToolSubnetA}, ${ToolSubnetB}
  VPCId:
    Description: AEM VPC Id
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-VPCId
    Value:
      Ref: VPCId
Parameters:
  AuthorDispatcherELBSubnetA:
    Description: The Author Dispatcher ELB Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  AuthorDispatcherELBSubnetB:
    Description: The Author Dispatcher ELB Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  AuthorDispatcherSubnetA:
    Description: The Author Dispatcher Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  AuthorDispatcherSubnetB:
    Description: The Author Dispatcher Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  AuthorPublishDispatcherSubnetA:
    Description: The Author Publish Dispatcher Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  AuthorPublishDispatcherSubnetB:
    Description: The Author Publish Dispatcher Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  AuthorSubnetA:
    Description: The Author Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  AuthorSubnetB:
    Description: The Author Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  PrivateRouteTable:
    Default: ''
    Description: The Private Route Table for AEM Stack VPC
    Type: String
  PublicRouteTable:
    Default: ''
    Description: The Public Route Table for AEM Stack VPC
    Type: String
  PublishDispatcherELBSubnetA:
    Description: The Publish Dispatcher ELB Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  PublishDispatcherELBSubnetB:
    Description: The Publish Dispatcher ELB Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  PublishDispatcherSubnetA:
    Description: The Publish Dispatcher Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  PublishDispatcherSubnetB:
    Description: The Publish Dispatcher Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  PublishSubnetA:
    Description: The Publish Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  PublishSubnetB:
    Description: The Publish Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  StackPrefix:
    Default: ''
    Description: Used to Namespace the Exported Resources
    Type: String
  ToolSubnetA:
    Default: ''
    Description: The Tool Subnet in Availability Zone A
    Type: AWS::EC2::Subnet::Id
  ToolSubnetB:
    Default: ''
    Description: The Tool Subnet in Availability Zone B
    Type: AWS::EC2::Subnet::Id
  VPCId:
    Description: AEM VPC Id
    Type: AWS::EC2::VPC::Id
Resources:
  DummyGroup:
    Properties:
      GroupDescription: Dummy Security Group to Allow Stack to Work
      VpcId:
        Ref: VPCId
    Type: AWS::EC2::SecurityGroup
