---

- name: Deploy AEM Stack Manager Cloud Native Implementation
  hosts: all
  gather_facts: no
  connection: local
  force_handlers: True

  tasks:
    - name: >
        Create AEM Stack Manager Resources
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ stack_manager.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: false
        template: "{{ playbook_dir }}/../../../../cloudformation/apps/stack-manager/main.yaml"
        template_parameters:
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
          S3DataStackManagerPrefix: "{{ stack_prefix }}/{{ stack_manager.s3_prefix }}"
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
      register: stack_info
      tags:
        - create

    - name: Create Stack Manager Task and SSM Document Name Mapping File
      command: >
        python "{{ playbook_dir }}"/../../../../stage/aem-stack-manager-cloud/scripts/create_config.py
               "{{ stack_prefix }}"
               "{{ stack_manager.ssm_stack_name }}"
               "{{ s3.data_bucket_name }}"
               "{{ stack_prefix }}/{{ stack_manager.s3_prefix }}"
               "{{ stack_info.stack_outputs.TaskStatusTopicArn }}"
               "{{ stack_info.stack_outputs.SSMServiceRoleArn }}"
               "{{ s3.data_bucket_name }}"
               "{{ stack_info.stack_outputs.BackupTopicArn }}"
               "{{ stack_info.stack_outputs.AemStackManagerTableName }}"
      tags:
        - create

    - name: Check if Stack Manager Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ stack_manager.stack_name }}"
             --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Manager Problem if Any
      debug:
        msg: Stack "{{stack_prefix }}-{{ stack_manager.stack_name }} does not exist or some other errors occured 
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Stack Manager Stack
      cloudformation:
        stack_name: "{{stack_prefix }}-{{ stack_manager.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
        - delete

  handlers:
    - name: Clean Up Temp Folder
      file:
        path: "../../../stage/aem-stack-manager-cloud"
        state: absent
