---
- name: Download library artifacts from public sites and upload them to an S3 bucket
  hosts: all
  gather_facts: no
  connection: local

  vars:
    artifacts_dir: ../../stage/library-artifacts/

  # Artifact download tasks unfortunately have to use a mix of proper get_url
  # and wget shell command. This is deliberately done in order to support environments
  # (a combination of older Ansible 2.x, Python 2.7.x, and OpenSSL 1.0x)
  # with tlsv1 protocol, which is used by GitHub, hence GitHub downloads use
  # command instead of get_url.

  tasks:

    - name: Ensure stage directory exists
      file:
        path: "{{ artifacts_dir }}"
        state: directory
        mode: 0755

    - name: Download AEM AWS Stack Provisioner from GitHub
      command: "wget -O {{ artifacts_dir }}/aem-aws-stack-provisioner-{{ library.aem_aws_stack_provisioner_version }}.tar.gz https://github.com/shinesolutions/aem-aws-stack-provisioner/releases/download/{{ library.aem_aws_stack_provisioner_version }}/aem-aws-stack-provisioner-{{ library.aem_aws_stack_provisioner_version }}.tar.gz"
      when: library.aem_aws_stack_provisioner_version is defined

    - name: Download AEM Orchestrator from Maven Central
      get_url:
        url: "http://central.maven.org/maven2/com/shinesolutions/aem-orchestrator/{{ library.aem_orchestrator_version }}/aem-orchestrator-{{ library.aem_orchestrator_version }}.jar"
        dest: "{{ artifacts_dir }}"
        mode: 0644
      when: library.aem_orchestrator_version is defined

    - name: Download AEM Password Reset from Maven Central
      get_url:
        url: "http://central.maven.org/maven2/com/shinesolutions/aem-password-reset-content/{{ library.aem_password_reset_version }}/aem-password-reset-content-{{ library.aem_password_reset_version }}.zip"
        dest: "{{ artifacts_dir }}"
        mode: 0644
      when: library.aem_password_reset_version is defined

    - name: Download AEM Stack Manager from GitHub
      command: "wget -O {{ artifacts_dir }}//aem-stack-manager-cloud-{{ library.aem_stack_manager_version }}.zip https://github.com/shinesolutions/aem-stack-manager-cloud/releases/download/{{ library.aem_stack_manager_version }}/aem-stack-manager-cloud-{{ library.aem_stack_manager_version }}.zip"
      when: library.aem_stack_manager_version is defined

    - name: Download Oak Run from Maven Central
      get_url:
        url: "http://central.maven.org/maven2/org/apache/jackrabbit/oak-run/{{ library.oak_run_version }}/oak-run-{{ library.oak_run_version }}.jar"
        dest: "{{ artifacts_dir }}"
        mode: 0644
      when: library.oak_run_version is defined

    - name: Download Simian Army from Bintray
      get_url:
        url: "https://dl.bintray.com/netflixoss/maven/com/netflix/simianarmy/simianarmy/{{ library.simian_army_version }}/simianarmy-{{ library.simian_army_version }}.war"
        dest: "{{ artifacts_dir }}"
        mode: 0644
      when: library.simian_army_version is defined

    - name: Upload fetched artifacts to S3 library bucket
      s3_sync:
        region: "{{ aws.region }}"
        bucket: "{{ s3.data_bucket_name }}"
        key_prefix: library
        file_root: "{{ artifacts_dir }}"
