---
- name: Set configuration tasks
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Add custom AWS Security Groups to CloudFormation template files for Publish Dispatcher ELB
      cf_secgrps:
        template_dir: "{{ item }}"
        elb_resource: 'PublishDispatcherLoadBalancer'
        secgrps: "{{ security_groups['publish_dispatcher_elb']['extra_groups'] }}"
      items:
        - ../../cloudformation/apps/aem/full-set/
      #register: cf_secgrps_out

    #- debug: var=cf_secgrps_out

    - name: Add custom AWS Security Groups to CloudFormation template files for Author Dispatcher ELB
      cf_secgrps:
        template_dir: "{{ item }}"
        elb_resource: 'AuthorDispatcherLoadBalancer'
        secgrps: "{{ security_groups['author_dispatcher_elb']['extra_groups'] }}"
      items:
        - ../../cloudformation/apps/aem/full-set/
     #register: cf_secgrps_out

    #- debug: var=cf_secgrps_out
