AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Chaos Monkey

Parameters:

  PrerequisitesStackPrefixParameter:
    Type: String
    Description: The AEM Stack Prerequisite Resources Stack Prefix

  MainStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  ChaosMonkeyImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Chaos Monkey Image Id

  ChaosMonkeyImageRootDevice:
    Type: String
    Description: The root device name for the Chaos Monkey Image Id
    Default: /dev/sda1

  ChaosMonkeyInstanceTypeParameter:
    Type: String
    Description: The Chaos Monkey Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  ChaosMonkeyASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Chaos Monkey Availability Zone List

  ChaosMonkeyRootVolSizeParameter:
    Type: Number
    Description: Chaos Monkey Instances Root EBS Volum Size

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Resources:

  ChaosMonkeyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: !Ref ChaosMonkeyImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: ChaosMonkeyRootVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${PrerequisitesStackPrefixParameter}-ChaosMonkeyInstanceProfile
      ImageId:
        Ref: ChaosMonkeyImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: ChaosMonkeyInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-ChaosMonkeySecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${MainStackPrefixParameter} chaos-monkey ${AemAwsStackProvisionerVersionParameter}\n"

  ChaosMonkeyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: ChaosMonkeyASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: ChaosMonkeyLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      Tags:
      - Key: Name
        Value: AEM Chaos Monkey
        PropagateAtLaunch: true
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
        PropagateAtLaunch: true
      - Key: Component
        Value: chaos-monkey
        PropagateAtLaunch: true
      - Key: OrchestratorASG
        Value:
          Fn::ImportValue:
            Fn::Sub: "${MainStackPrefixParameter}-OrchestratorAutoScalingGroup"
        PropagateAtLaunch: true
      - Key: PublisherASG
        Value:
          Fn::ImportValue:
            Fn::Sub: "${MainStackPrefixParameter}-PublishAutoScalingGroup"
        PropagateAtLaunch: true
      - Key: PublisherDispatcherASG
        Value:
          Fn::ImportValue:
            Fn::Sub: "${MainStackPrefixParameter}-PublishDispatcherAutoScalingGroup"
        PropagateAtLaunch: true
      - Key: AuthorDispatcherASG
        Value:
          Fn::ImportValue:
            Fn::Sub: "${MainStackPrefixParameter}-AuthorDispatcherAutoScalingGroup"
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              !Sub ${NetworkStackPrefixParameter}-ChaosMonkeySubnetList
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupMinSize"
            - "GroupMaxSize"
            - "GroupDesiredCapacity"
            - "GroupInServiceInstances"
            - "GroupPendingInstances"
            - "GroupStandbyInstances"
            - "GroupTerminatingInstances"
            - "GroupTotalInstances"

Outputs:

  ChaosMonkeyLaunchConfiguration:
    Value:
      Ref: ChaosMonkeyLaunchConfiguration
    Description: The Chaos Monkey Launch Configuration

  ChaosMonkeyAutoScalingGroup:
    Value:
      Ref: ChaosMonkeyAutoScalingGroup
    Description: The Chaos Monkey Auto Scaling Group
