---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create Messaging resources for the AEM Stack Auto Scaling Group Events

Parameters:

  MessagingStackPrefixParameter:
    Type: String
    Description: The AEM Stack Messaging Resources Stack Prefix

  AEMASGEventQueueNameParameter:
    Type: String
    Description: The AEM Stack Auto Scaling Group Event Quene Name

  AEMASGEventTopicDisplayNameParameter:
    Type: String
    Description: The AEM Stack Auto Scaling Group Event Topic Display Name

  AEMASGEventTopicNameParameter:
    Type: String
    Description: The AEM Stack Auto Scaling Group Event Topic Name

  AEMCWEventNotificationEmail:
    Type: String
    Description: The EMail adress for sending CW Alarm messages

Resources:

  AEMAutoScalingGroupEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Ref: AEMASGEventQueueNameParameter
      VisibilityTimeout: 60

  AEMASGEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Ref: AEMASGEventTopicDisplayNameParameter
      Subscription:
        - Endpoint:
            Fn::GetAtt: [ AEMAutoScalingGroupEventQueue, Arn ]
          Protocol: sqs
      TopicName:
        Ref: AEMASGEventTopicNameParameter

  AEMASGEventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - sqs:SendMessage
            Resource:
              - Fn::GetAtt: [ AEMAutoScalingGroupEventQueue, Arn ]
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: AEMASGEventTopic
      Queues:
        - Ref: AEMAutoScalingGroupEventQueue

  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${MessagingStackPrefixParameter}-alarm-notification-topic
      Subscription:
        - Endpoint: !Ref AEMCWEventNotificationEmail
          Protocol: email

  AEMASGEventQueueLengthHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if queue length avg > 10 for 2 minutes"
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      TreatMissingData: ignore
      ActionsEnabled: true
      AlarmActions:
        - Ref: AlarmNotificationTopic
      Dimensions:
        - Name: QueueName
          Value: !Ref AEMASGEventQueueNameParameter
      ComparisonOperator: GreaterThanThreshold

Outputs:

  AEMAutoScalingGroupEventQueue:
    Value:
      Ref: AEMAutoScalingGroupEventQueue
    Description: The AEM ASG Event Queue

  AEMASGEventQueueName:
    Value: !GetAtt AEMAutoScalingGroupEventQueue.QueueName
    Description: The AEM ASG Event Queue Name
    Export:
      Name:
        Fn::Sub: ${MessagingStackPrefixParameter}-AEMASGEventQueueName

  AEMASGEventTopic:
    Value:
      Ref: AEMASGEventTopic
    Description: The AEM ASG Event Topic
    Export:
      Name:
        Fn::Sub: ${MessagingStackPrefixParameter}-AEMASGEventTopic

  AlarmNotificationTopic:
    Value:
      Ref: AlarmNotificationTopic
    Description: The AEM Alarm Notification Topic
    Export:
      Name:
        Fn::Sub: ${MessagingStackPrefixParameter}-AlarmNotificationTopic
