AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Publish

Parameters:

  InstanceProfilesStackPrefixParameter:
    Type: String
    Description: The AEM Stack Instance Profile Stack Prefix

  MessagingStackPrefixParameter:
    Type: String
    Description: The AEM Stack Messaging Stack Prefix

  SecurityGroupsStackPrefixParameter:
    Type: String
    Description: The AEM Stack Security Groups Resources Stack Prefix

  MainStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  PublishImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Publish Image Id

  PublishImageRootDevice:
    Type: String
    Description: The root device name for the Publish Image Id
    Default: /dev/sda1

  PublishInstanceTypeParameter:
    Type: String
    Description: The Publish Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  PublishASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Publish Availability Zone List

  PublishASGMaxSizeParameter:
    Type: String
    Description: The Publish Auto Scaling Group Maximum Size

  PublishASGMinSizeParameter:
    Type: String
    Description: The Publish Auto Scaling Group Minimum Size

  PublishASGDesiredCapacityParameter:
    Type: String
    Description: The Publish Auto Scaling Group Desired Capacity

  PublishRootVolSizeParameter:
    Type: Number
    Description: Publish Instances Root EBS Volume Size

  PublishDataVolSizeParameter:
    Type: Number
    Description: The Publish Instances Data EBS Volume Size

  UsePublishDataVolSnapshotParameter:
    Type: String
    AllowedValues: [true, false]
    Description: Wheather to use the Publish Snapshot Data Volume.

  PublishDataVolSnapshotParameter:
    Type: String
    Description: The Publish Data Volume Snapshot Id

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Conditions:
  UsePublishDataVolSnapshotCondition:
    Fn::Equals:
      - Ref: UsePublishDataVolSnapshotParameter
      - true

Resources:

  PublishLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: !Ref PublishImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDataVolSizeParameter
          VolumeType: gp2
          SnapshotId:
            Fn::If:
              - UsePublishDataVolSnapshotCondition
              - Ref: PublishDataVolSnapshotParameter
              - Ref: AWS::NoValue
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${InstanceProfilesStackPrefixParameter}-PublishInstanceProfile
      ImageId:
        Ref: PublishImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackPrefixParameter}-PublishSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${MainStackPrefixParameter} publish ${AemAwsStackProvisionerVersionParameter}\n"

  PublishAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: PublishASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 900
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: PublishLaunchConfiguration
      MaxSize:
        Ref: PublishASGMaxSizeParameter
      MinSize:
        Ref: PublishASGMinSizeParameter
      DesiredCapacity:
        Ref: PublishASGDesiredCapacityParameter
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN:
          Fn::ImportValue:
            Fn::Sub: ${MessagingStackPrefixParameter}-AEMASGEventTopic
      Tags:
      - Key: Name
        Value: AEM Publish
        PropagateAtLaunch: true
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
        PropagateAtLaunch: true
      - Key: Component
        Value: publish
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              !Sub ${NetworkStackPrefixParameter}-PublishSubnetList
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupMinSize"
            - "GroupMaxSize"
            - "GroupDesiredCapacity"
            - "GroupInServiceInstances"
            - "GroupPendingInstances"
            - "GroupStandbyInstances"
            - "GroupTerminatingInstances"
            - "GroupTotalInstances"

Outputs:

  PublishLaunchConfiguration:
    Value:
      Ref: PublishLaunchConfiguration
    Description: The Publish Launch Configuration

  PublishAutoScalingGroup:
    Value:
      Ref: PublishAutoScalingGroup
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-PublishAutoScalingGroup
    Description: The Publish Auto Scaling Group
