---

- name: Deploy AEM Stack Manager Cloud Native Implementation
  hosts: all
  gather_facts: no
  connection: local
  force_handlers: True

  tasks:
    - name: Generate CloudFormation Template for SSM Documents
      shell: >
          "{{ playbook_dir }}/../../../../stage/aem-stack-manager-cloud/scripts/generate.sh" >  "{{ playbook_dir }}/../../../../stage/ssm_template.json"
      tags:
        - create

    - name: Create SSM Document Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ stack_manager.ssm_stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: false
        template: "{{ playbook_dir }}/../../../../stage/ssm_template.json"
      tags:
        - create

    - name: Check if Stack Manager SSM Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{stack_prefix }}-{{ stack_manager.ssm_stack_name }}"
             --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report SSM Document Stack Problem if Any
      debug:
        msg: Stack "{{stack_prefix }}-{{ stack_manager.ssm_stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Stack Manager SSM Document Stack
      cloudformation:
        stack_name: "{{stack_prefix }}-{{ stack_manager.ssm_stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
        - delete
