AWSTemplateFormatVersion: '2010-09-09'

Description: Create AEM Consolidated Compute Resources Stacks

Parameters:

  MainStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  InstanceProfilesStackPrefixParameter:
    Type: String
    Description: The Author Instance Profiles Resources Stack Prefix

  SecurityGroupStackPrefixParameter:
    Type: String
    Description: The AEM Stack Security Groups Resources Stack Prefix

  AuthorPublishDispatcherImageParameter:
    Type: AWS::EC2::Image::Id
    Description: AMI Id used for the Host

  AuthorPublishDispatcherImageRootDevice:
    Type: String
    Description: The root device name for the Author Publish Dispatcher Image Id
    Default: /dev/sda1

  AuthorPublishDispatcherInstanceTypeParameter:
    Type: String
    Description: The Author Publish Dispatcher Instance Type

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound from Bastion Host Security Group Id

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  AuthorPublishDispatcherRootVolSizeParameter:
    Type: Number
    Description: Author Publish Dispatcher Instances Root EBS Volume Size

  AuthorPublishDispatcherDataVolSizeParameter:
    Type: Number
    Description: Author Publish Dispatcher Instances Data EBS Volume Size

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

  AssociatePublicIpAddressParameter:
    Type: String
    Description: Add Public IP Address to instance

  Route53HostedZoneNameParameter:
    Type: String
    Description: Route53 Hosted Zone Name the Record Set will be Created in

  AuthorPublishDispatcherDNSRecordSetNameParameter:
    Type: String
    Description: Author Publish Dispatcher DNS Record Set Name

  DNSRecordSetTTL:
    Type: String
    Description: Record Set TTL value

Resources:

  AuthorPublishDispatcherInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName:
          Ref: AuthorPublishDispatcherImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdc
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${InstanceProfilesStackPrefixParameter}-AuthorPublishDispatcherInstanceProfile
      ImageId:
        Ref: AuthorPublishDispatcherImageParameter
      InstanceType:
        Ref: AuthorPublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      NetworkInterfaces:
      - AssociatePublicIpAddress:
          Ref: AssociatePublicIpAddressParameter
        DeviceIndex: '0'
        GroupSet:
          - Ref: InboundFromBastionHostSecurityGroupParameter
          - Fn::ImportValue: !Sub ${SecurityGroupStackPrefixParameter}-AuthorPublishDispatcherSecurityGroup
        SubnetId:
          Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-AuthorPublishDispatcherSubnetA
      Tags:
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
      - Key: Name
        Value: AuthorPublishDispatcher
      - Key: Component
        Value: author-publish-dispatcher
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} author-publish-dispatcher\
            \ ${AemAwsStackProvisionerVersionParameter}\n"

  AuthorPublishDispatcherRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        Ref: Route53HostedZoneNameParameter
      Name:
        Fn::Sub: ${AuthorPublishDispatcherDNSRecordSetNameParameter}.${Route53HostedZoneNameParameter}
      ResourceRecords:
      - Fn::GetAtt: [AuthorPublishDispatcherInstance, PrivateIp]
      TTL:
        Ref: DNSRecordSetTTL
      Type: A
